# -*- coding: utf-8 -*-
"""Materi-11_support_vector_contoh_svmTrapezoid.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16wXf93luwDPivRCj9kdu1q2dUS1A4HkH
"""

# Import library yang diperlukan
import numpy as np
import pandas as pd
from sklearn import svm
from google.colab import drive
import matplotlib.pyplot as plt

# Mount Google Drive
drive.mount('/content/drive')

# Path ke file Database.txt di Google Drive
file_path = '/content/drive/My Drive/modul11' # Ganti dengan path sesuai lokasi file di google drive